name: 'Dev - PR Close'

on:
  push:
    branches:
      - main

jobs: 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_ORG_PAT }}
        
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
        
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
          
      - name: Apply version bump
        run: | 
          npm version patch
          
      - name: Git push version bump
        run: git push origin main --follow-tags --force
        
      - id: set-version
        name: Output version change
