name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Git commands
      run: |
        git config --global user.email "omprakashkartik82280@gmail.com"
        git config --global user.name "kom50"

        # Install depedencies
        npm i

        ls

        rm -rf dist
        ls

        # build
        npm run build

        # navigate into the build output directory
        # cd dist

        echo 'Deploying to gh-pages...'
        # git init
        # git checkout -b main
        # git add -A
        # git commit -m 'Deploying to gh-pages"' 
        # git push origin main:gh-pages
        ls
        git pull origin gh-pages
        git add dist -f
        git commit -m 'Deploying to gh-pages"' 
        git subtree push --prefix dist origin gh-pages
        # git subtree push --prefix dist origin gh-pages -f

        echo 'Done'
      env:
        github-token: ${{ secrets.GH_TOKEN }}
