name: Git Commands Example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Git commands
      run: |
        git config --global user.email "omprakashkartik82280@gmail.com"
        git config --global user.name "kom50"
        git checkout -b om
        echo "Hello, world!" > file.txt
        git add .
        git commit -m "Commit message"
        git push
